import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { CopyPmBriefLink } from "@/components/portfolio-iq/CopyPmBriefLink";
import { DwellsyIqWorkspaceNav } from "@/components/dwellsy-iq/DwellsyIqWorkspaceNav";
import { getActiveOrgContext } from "@/lib/auth/active-org";
import { isMarketEntitled, resolveViewerEntitlement } from "@/lib/auth/market-entitlements.server";
import { viewerHasProductAccess } from "@/lib/auth/product-entitlements.server";
import { portfolioIqPreviewEnabled } from "@/lib/portfolio-iq/feature";
import { buildPmBriefSnapshotFromComposer, loadPortfolioIqPmBriefComposer } from "@/lib/portfolio-iq/pm-brief.server";
import { publishPortfolioIqPmBrief, revokePortfolioIqPmBrief } from "@/app/portfolio-iq/pm-brief-actions";

export const dynamic = "force-dynamic";

function money(value: number | null): string { return value === null ? "Not enough evidence" : `$${Math.round(value).toLocaleString("en-US")}`; }
function percent(value: number | null): string { return value === null ? "Not enough evidence" : `${value >= 0 ? "+" : ""}${value.toFixed(1)}%`; }
function dateLabel(value: Date | string | null): string { return value ? new Date(value).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }) : "Not set"; }

export default async function PortfolioIqPmBriefComposerPage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ signalId?: string }> }) {
  if (!portfolioIqPreviewEnabled() || !(await viewerHasProductAccess("portfolio_iq"))) notFound();
  const { userId, organizationId } = await getActiveOrgContext();
  if (!userId) notFound();
  if (!organizationId) redirect("/setup-workspace");
  const { slug } = await params;
  const query = await searchParams;
  const composer = await loadPortfolioIqPmBriefComposer({ userId, organizationId, slug, signalId: query.signalId });
  if (!composer) notFound();
  const entitlement = await resolveViewerEntitlement();
  if (!isMarketEntitled(entitlement, composer.property.portfolio.marketId)) notFound();
  const preview = composer.signal ? buildPmBriefSnapshotFromComposer({ composer, publishedAt: new Date(), ownerNote: null, responseDueAt: null }) : null;
  const activeBrief = composer.signal ? composer.briefs.find((brief) => brief.signalId === composer.signal?.id && ["published", "responded"].includes(brief.status)) ?? null : null;

  return <main className="mx-auto w-full max-w-7xl px-5 py-8 sm:px-6 lg:px-10 lg:py-10">
    <DwellsyIqWorkspaceNav />
    <nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap items-center gap-2 text-xs font-semibold text-muted-foreground"><Link href={`/portfolio-iq/properties/${slug}`} className="hover:text-teal-700">{composer.property.asset.name}</Link><span>/</span><span>PM brief</span></nav>
    <header className="grid gap-7 border-b border-grid pb-8 lg:grid-cols-[1fr_360px] lg:items-end"><div><p className="dq-eyebrow">PM collaboration</p><h1 className="dq-h1">Prepare a focused property brief</h1><p className="mt-3 max-w-3xl text-[15px] leading-6 text-muted-foreground">Share one evidence-backed question with the property manager without exposing the rest of the portfolio or any Operator IQ ranking.</p></div><aside className="rounded-xl border border-teal/25 bg-teal-soft p-5"><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-teal-700">Sharing boundary</p><p className="mt-2 text-lg font-semibold text-navy">One property · one issue</p><p className="mt-2 text-sm leading-6 text-foreground/75">Publication freezes the PM-safe evidence. The link can be revoked at any time.</p></aside></header>

    <section className="mt-8 grid gap-6 lg:grid-cols-[0.72fr_1.28fr]">
      <aside className="space-y-6"><section className="rounded-xl border border-grid bg-white p-5"><p className="dq-eyebrow">Choose the discussion</p><h2 className="dq-h2">Current property issues</h2>{composer.property.signals.length ? <div className="mt-4 space-y-2">{composer.property.signals.slice(0, 8).map((signal) => <Link key={signal.id} href={`/portfolio-iq/properties/${slug}/pm-brief?signalId=${signal.id}`} className={`block rounded-lg border p-3 text-sm ${composer.signal?.id === signal.id ? "border-navy bg-navy text-white" : "border-grid bg-white text-navy hover:bg-surface-soft"}`}><span className="font-semibold">{signal.headline}</span><span className={`mt-1 block text-xs ${composer.signal?.id === signal.id ? "text-white/70" : "text-muted-foreground"}`}>{signal.severity} priority · {signal.category}</span></Link>)}</div> : <p className="mt-3 text-sm leading-6 text-muted-foreground">No active evidence-backed issue is available for a PM brief.</p>}</section>
      <section className="rounded-xl border border-grid bg-white p-5"><p className="dq-eyebrow">Prior outreach</p><h2 className="dq-h2">Brief history</h2>{composer.briefs.length ? <div className="mt-4 divide-y divide-grid">{composer.briefs.map((brief) => <div key={brief.id} className="py-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-navy">{brief.signal.headline}</p><p className="mt-1 text-xs capitalize text-muted-foreground">{brief.status} · {dateLabel(brief.publishedAt)}</p></div>{brief.status !== "revoked" && <Link href={`/pm-briefs/${brief.publicToken}`} target="_blank" className="text-xs font-semibold text-teal-700 hover:underline">Open</Link>}</div>{brief.response && <div className="mt-3 rounded-lg bg-teal-soft p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-teal-700">PM response</p><p className="mt-1 text-xs font-semibold text-navy">{brief.response.responderName}</p><p className="mt-1 text-xs leading-5 text-foreground/75">{brief.response.responseSummary}</p>{brief.response.actionPlan && <p className="mt-2 text-xs leading-5 text-navy"><strong>Action:</strong> {brief.response.actionPlan}</p>}</div>}</div>)}</div> : <p className="mt-3 text-sm text-muted-foreground">No PM briefs have been published for this property.</p>}</section></aside>

      <div className="space-y-6">{preview && composer.signal ? <>
        <article className="overflow-hidden rounded-xl border border-grid bg-white shadow-sm"><div className="border-b border-grid p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><p className="dq-eyebrow">PM-facing preview</p><span className="rounded-full bg-surface-soft px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">No Operator IQ ranking</span></div><h2 className="mt-2 text-2xl font-semibold leading-8 text-navy">{preview.issue.headline}</h2><p className="mt-2 text-sm leading-6 text-foreground/75">{preview.issue.narrative}</p></div><div className="grid gap-px bg-grid sm:grid-cols-2 lg:grid-cols-4">{[["Observed asking rent", money(preview.evidence.askingRent), `${preview.evidence.observationCount} observations`], ["90-day movement", percent(preview.evidence.askingRentChange90d), "Advertised asking rent"], ["Listing velocity", preview.evidence.medianDom === null ? "Not enough evidence" : `${Math.round(preview.evidence.medianDom)} days`, "Advertised-market duration"], ["Position vs comps", percent(preview.evidence.askingRentVsComps), preview.evidence.compStatus === "locked" ? `${preview.evidence.compCount} approved comps` : "Not shown until locked"]].map(([label, value, detail]) => <section key={label} className="bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 text-lg font-semibold text-navy">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></section>)}</div><div className="border-t border-grid p-5 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-wider text-teal-700">Questions for the manager</p><ol className="mt-3 space-y-2">{preview.request.questions.map((question, index) => <li key={question} className="flex gap-3 text-sm leading-6 text-navy"><span className="font-bold text-teal-700">{index + 1}.</span><span>{question}</span></li>)}</ol></div></article>
        {activeBrief ? <section className="rounded-xl border border-emerald-200 bg-emerald-50 p-5 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-wider text-emerald-800">Brief {activeBrief.status}</p><h2 className="mt-2 text-xl font-semibold text-navy">The property-scoped link is ready</h2><p className="mt-2 text-sm leading-6 text-emerald-900/80">Only the evidence shown in the PM-facing preview is available through this link.</p><div className="mt-4 flex flex-wrap gap-3"><CopyPmBriefLink path={`/pm-briefs/${activeBrief.publicToken}`} /><Link href={`/pm-briefs/${activeBrief.publicToken}`} target="_blank" className="rounded-md bg-navy px-3 py-2 text-xs font-semibold text-white">Open PM view</Link>{activeBrief.status === "published" && <form action={revokePortfolioIqPmBrief}><input type="hidden" name="briefId" value={activeBrief.id} /><input type="hidden" name="slug" value={slug} /><button className="rounded-md border border-rose-300 bg-white px-3 py-2 text-xs font-semibold text-rose-800">Revoke link</button></form>}</div></section> : <section className="rounded-xl border border-navy bg-navy p-5 text-white sm:p-6"><p className="text-[10px] font-bold uppercase tracking-wider text-teal-200">Publish brief</p><h2 className="mt-2 text-2xl font-semibold">Ask for operating context</h2><form action={publishPortfolioIqPmBrief} className="mt-5 grid gap-4 sm:grid-cols-2"><input type="hidden" name="slug" value={slug} /><input type="hidden" name="signalId" value={composer.signal.id} /><label className="sm:col-span-2 text-sm font-semibold">Optional owner note<textarea name="ownerNote" maxLength={1000} rows={3} placeholder="Add property-specific context or the decision you need to make." className="mt-2 w-full rounded-md border border-white/20 bg-white px-3 py-2.5 text-sm font-normal leading-6 text-navy" /></label><label className="text-sm font-semibold">Response requested by<input type="date" name="responseDueAt" className="mt-2 w-full rounded-md border border-white/20 bg-white px-3 py-2.5 text-sm font-normal text-navy" /></label><div className="flex items-end"><button className="w-full rounded-md bg-white px-4 py-2.5 text-sm font-semibold text-navy">Publish restricted PM brief</button></div></form><p className="mt-4 text-xs leading-5 text-white/65">Publishing creates a revocable, unguessable link. It does not send email automatically.</p></section>}
      </> : <div className="rounded-xl border border-dashed border-grid bg-white px-6 py-12 text-center"><h2 className="text-xl font-semibold text-navy">Select an active issue</h2><p className="mt-2 text-sm text-muted-foreground">The PM brief needs one evidence-backed property question.</p></div>}</div>
    </section>
  </main>;
}
