import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { DwellsyIqWorkspaceNav } from "@/components/dwellsy-iq/DwellsyIqWorkspaceNav";
import { getActiveOrgContext } from "@/lib/auth/active-org";
import { viewerHasProductAccess } from "@/lib/auth/product-entitlements.server";
import { portfolioIqPreviewEnabled } from "@/lib/portfolio-iq/feature";
import { loadPortfolioIqOutcomes } from "@/lib/portfolio-iq/outcome-review.server";
import { saveOutcomeReview } from "./actions";

export const dynamic = "force-dynamic";
function date(value: string | Date | null | undefined): string { if (!value) return "Not available"; return new Date(value).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }); }
function value(number: number | null, unit: string): string { if (number === null) return "Not available"; if (unit === "dollars") return `$${Math.round(number).toLocaleString("en-US")}`; if (unit === "percent") return `${number > 0 ? "+" : ""}${number.toFixed(1)}%`; if (unit === "days") return `${Math.round(number)} days`; return Math.round(number).toLocaleString("en-US"); }

export default async function OutcomesPage() {
  if (!portfolioIqPreviewEnabled() || !(await viewerHasProductAccess("portfolio_iq"))) notFound();
  const { userId, organizationId } = await getActiveOrgContext(); if (!userId) notFound(); if (!organizationId) redirect("/setup-workspace");
  const data = await loadPortfolioIqOutcomes({ userId, organizationId }); if (!data) notFound();
  return <main className="mx-auto w-full max-w-7xl px-5 py-8 sm:px-6 lg:px-10 lg:py-10"><DwellsyIqWorkspaceNav/>
    <header className="grid gap-6 border-b border-grid pb-8 lg:grid-cols-[1fr_360px] lg:items-end"><div><p className="dq-eyebrow">Decision follow-through</p><h1 className="dq-h1">Outcome Reviews</h1><p className="mt-3 max-w-3xl text-[15px] leading-6 text-muted-foreground">Compare each accepted action plan with later asking-market evidence, record the owner&apos;s conclusion, and decide what should happen next.</p></div><aside className="rounded-xl border border-teal/25 bg-teal-soft p-5"><p className="text-[10px] font-bold uppercase tracking-wider text-teal-700">Evidence rule</p><p className="mt-2 text-sm leading-6 text-navy">A source cutoff must advance beyond the frozen decision baseline before this page presents a measurable outcome.</p></aside></header>
    <section className="mt-7 grid gap-px overflow-hidden rounded-xl border border-grid bg-grid sm:grid-cols-4">{[["Due now",data.dueCount],["Ready to review",data.readyCount],["Waiting for source",data.waitingCount],["Reviewed",data.reviewedCount]].map(([label,count]) => <article key={String(label)} className="bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold text-navy">{count}</p></article>)}</section>
    <section className="mt-10 space-y-5">{data.items.length === 0 ? <div className="rounded-xl border border-dashed border-grid px-6 py-14 text-center"><h2 className="text-xl font-semibold text-navy">No monitored decisions yet</h2><p className="mt-2 text-sm text-muted-foreground">Start a decision case from Today to establish a baseline and follow-up window.</p></div> : data.items.map(({decision, comparison, liveComparison, savedReview, due}) => <article key={decision.id} className="overflow-hidden rounded-xl border border-grid bg-white shadow-sm">
      <div className="grid gap-5 border-b border-grid p-5 sm:p-6 lg:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap gap-2 text-[10px] font-bold uppercase tracking-wider"><span className="text-teal-700">{decision.signal.asset?.name ?? "Portfolio decision"}</span>{due && !savedReview?.reviewedAt && <span className="rounded-full bg-rose-100 px-2 py-0.5 text-rose-800">Review due</span>}<span className={`rounded-full px-2 py-0.5 ${liveComparison.sourceHealth === "healthy" ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>{liveComparison.sourceHealth === "healthy" ? "New evidence" : "Source unchanged"}</span></div><h2 className="mt-2 text-xl font-semibold text-navy">{decision.signal.headline}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{comparison.sourceMessage}</p></div><Link href={`/today/cases/${decision.signalId}`} className="h-fit rounded-md border border-navy px-4 py-2 text-sm font-semibold text-navy">Open decision case</Link></div>
      <div className="grid gap-px bg-grid lg:grid-cols-4">{comparison.metrics.map((metric) => <div key={metric.label} className="bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{metric.label}</p><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-muted-foreground">Baseline</p><p className="mt-1 font-semibold text-navy">{value(metric.baseline,metric.unit)}</p></div><div><p className="text-xs text-muted-foreground">Current</p><p className="mt-1 font-semibold text-navy">{value(metric.current,metric.unit)}</p></div></div></div>)}</div>
      <div className="grid gap-6 border-t border-grid p-5 sm:p-6 lg:grid-cols-[1fr_420px]"><div><p className="text-[10px] font-bold uppercase tracking-wider text-teal-700">What we agreed to do</p><p className="mt-2 text-sm leading-6 text-navy">{decision.actionPlan ?? "Action plan not recorded"}</p><p className="mt-4 text-[10px] font-bold uppercase tracking-wider text-teal-700">How we said we would judge it</p><p className="mt-2 text-sm leading-6 text-navy">{decision.successMeasure ?? "Success measure not recorded"}</p><p className="mt-4 text-xs text-muted-foreground">Baseline source through {date(comparison.baselineAvailableThrough)} · Current source through {date(liveComparison.currentAvailableThrough)}</p></div>
      {savedReview?.reviewedAt ? <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-emerald-800">Owner review recorded</p><p className="mt-2 text-lg font-semibold capitalize text-navy">{savedReview.conclusion}</p><p className="mt-2 text-sm leading-6 text-navy">{savedReview.reviewNote}</p>{savedReview.nextReviewAt && <p className="mt-3 text-xs text-emerald-900">Review again {date(savedReview.nextReviewAt)}</p>}</div> : <form action={saveOutcomeReview} className="rounded-lg border border-grid bg-surface-soft p-4"><input type="hidden" name="signalId" value={decision.signalId}/><label className="text-xs font-semibold text-navy">Owner conclusion<select name="conclusion" defaultValue={liveComparison.sourceHealth === "healthy" ? "unchanged" : "inconclusive"} className="mt-2 w-full rounded-md border border-grid bg-white px-3 py-2 text-sm font-normal">{liveComparison.sourceHealth === "healthy" && <><option value="improved">Improved</option><option value="unchanged">Unchanged</option><option value="worsened">Worsened</option></>}<option value="inconclusive">Inconclusive</option></select></label><label className="mt-3 block text-xs font-semibold text-navy">Review note<textarea name="reviewNote" required rows={3} placeholder={liveComparison.sourceHealth === "healthy" ? "Explain what changed and the next decision." : "Record why the review remains inconclusive."} className="mt-2 w-full rounded-md border border-grid bg-white px-3 py-2 text-sm font-normal leading-5"/></label><label className="mt-3 block text-xs font-semibold text-navy">Next review date<input name="nextReviewAt" type="date" className="mt-2 w-full rounded-md border border-grid bg-white px-3 py-2 text-sm font-normal"/></label><button className="mt-4 w-full rounded-md bg-navy px-4 py-2.5 text-sm font-semibold text-white">Record outcome review</button></form>}
      </div>
    </article>)}</section>
  </main>;
}
