import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import type { MarketIqMarketCell, MarketIqReportSnapshot } from "@/lib/market-iq/report/report";

const colors = { body: "#334155", muted: "#64748B", line: "#D7DEE7", soft: "#F3F6F7", white: "#FFFFFF" };
const styles = StyleSheet.create({
  page: { backgroundColor: colors.white, color: colors.body, fontFamily: "Helvetica", fontSize: 8, paddingBottom: 42, paddingHorizontal: 44, paddingTop: 38 },
  between: { display: "flex", flexDirection: "row", justifyContent: "space-between" },
  brand: { fontSize: 15, fontWeight: 700 }, overline: { fontSize: 7, fontWeight: 700, letterSpacing: 1.1, textTransform: "uppercase" },
  date: { color: colors.muted, fontSize: 7, textAlign: "right" }, rule: { borderTopColor: colors.line, borderTopWidth: 1, marginTop: 14 },
  hero: { marginTop: 31, maxWidth: 500 }, title: { fontSize: 28, fontWeight: 700, lineHeight: 1.08, marginTop: 8 },
  narrative: { color: colors.body, fontSize: 10, lineHeight: 1.55, marginTop: 13 }, scope: { borderRadius: 7, marginTop: 21, padding: 15 },
  scopeValue: { color: colors.white, fontSize: 18, fontWeight: 700, marginTop: 4 }, scopeText: { color: "#DDE7EA", fontSize: 8, marginTop: 4 },
  section: { marginTop: 27 }, sectionTitle: { fontSize: 17, fontWeight: 700, marginTop: 5 }, sectionIntro: { color: colors.body, fontSize: 9, lineHeight: 1.5, marginTop: 6 },
  cards: { display: "flex", flexDirection: "row", flexWrap: "wrap", gap: 9, marginTop: 14 }, card: { borderColor: colors.line, borderRadius: 6, borderWidth: 1, minHeight: 110, padding: 11, width: "31.8%" },
  cardValue: { fontSize: 17, fontWeight: 700, marginTop: 9 }, cardTrend: { fontSize: 8, fontWeight: 700, marginTop: 3 }, cardMeta: { borderTopColor: colors.line, borderTopWidth: 1, color: colors.muted, fontSize: 6.8, lineHeight: 1.4, marginTop: 9, paddingTop: 7 },
  table: { borderColor: colors.line, borderRadius: 6, borderWidth: 1, marginTop: 14 }, tableHeader: { backgroundColor: colors.soft, display: "flex", flexDirection: "row", paddingHorizontal: 8, paddingVertical: 7 },
  tableRow: { borderTopColor: colors.line, borderTopWidth: 1, display: "flex", flexDirection: "row", paddingHorizontal: 8, paddingVertical: 8 },
  c1: { width: "18%" }, c2: { width: "23%" }, c3: { width: "15%" }, c4: { width: "14%" }, c5: { width: "20%" }, c6: { width: "10%" },
  tableLabel: { color: colors.muted, fontSize: 6.2, fontWeight: 700, letterSpacing: 0.4, textTransform: "uppercase" },
  context: { borderRadius: 7, marginTop: 15, padding: 16 }, contextTitle: { color: colors.white, fontSize: 17, fontWeight: 700, marginTop: 7 }, contextText: { color: "#DFE7EC", fontSize: 9, lineHeight: 1.55, marginTop: 9 },
  metricRow: { display: "flex", flexDirection: "row", gap: 9, marginTop: 12 }, metric: { backgroundColor: colors.soft, borderRadius: 6, padding: 11, width: "24%" }, metricValue: { fontSize: 14, fontWeight: 700, marginTop: 5 },
  source: { borderTopColor: colors.line, borderTopWidth: 1, marginTop: 12, paddingTop: 10 }, sourceName: { fontSize: 8, fontWeight: 700 }, sourceText: { color: colors.muted, fontSize: 7.5, lineHeight: 1.45, marginTop: 3 },
  disclosure: { backgroundColor: colors.soft, borderRadius: 6, color: colors.body, fontSize: 8, lineHeight: 1.5, marginTop: 18, padding: 12 },
  footerLeft: { bottom: 20, color: colors.muted, fontSize: 6.5, left: 44, position: "absolute" }, footerRight: { bottom: 20, color: colors.muted, fontSize: 6.5, position: "absolute", right: 44, textAlign: "right", width: 210 },
});

function safeColor(value: string, fallback: string) { return /^#[0-9a-f]{6}$/i.test(value) ? value : fallback; }
function money(value: number | null) { return value === null ? "Not published" : `$${Math.round(value).toLocaleString("en-US")}`; }
function trend(cell: MarketIqMarketCell) { if (!cell.trajectory) return "Trajectory not published"; const value = cell.trajectory.yearOverYearPct; return `${value >= 0 ? "+" : ""}${value.toFixed(1)}% year over year`; }
function reportDate(value: string) { return new Date(value).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric", timeZone: "UTC" }); }

function Card({ cell, primary, accent }: { cell: MarketIqMarketCell; primary: string; accent: string }) {
  return <View style={styles.card} wrap={false}><Text style={[styles.overline, { color: colors.muted }]}>{cell.geographyLabel}</Text><Text style={[{ fontSize: 8, fontWeight: 700, marginTop: 4 }, { color: primary }]}>{cell.label}</Text><Text style={[styles.cardValue, { color: primary }]}>{money(cell.rentLevel.medianAskingRent)}</Text><Text style={[styles.cardTrend, { color: cell.trajectory ? accent : colors.muted }]}>{trend(cell)}</Text><Text style={styles.cardMeta}>${cell.rentLevel.medianRentPerSqFt?.toFixed(2) ?? "N/A"} per sf | N={cell.rentLevel.observations.toLocaleString("en-US")} | through {cell.rentLevel.availableThrough}</Text></View>;
}
function Footer({ brand, pageNumber }: { brand: string; pageNumber: number }) { return <><Text style={styles.footerLeft} fixed>Prepared by {brand}</Text><Text style={styles.footerRight} fixed>Market data by Dwellsy IQ  |  {pageNumber} of 3</Text></>; }

export function MarketIqReportPDF({ report }: { report: MarketIqReportSnapshot }) {
  const primary = safeColor(report.brand.primaryColor, "#173B57");
  const accent = safeColor(report.brand.accentColor, "#B96D3A");
  const cells = report.marketRead.cells.filter((cell) => cell.status === "reportable");
  const historical = report.marketConditions.historical;
  return <Document title={`${report.brand.displayName} | ${report.scope.marketName} local market read`} author={report.brand.displayName}>
    <Page size="LETTER" style={styles.page}><View style={styles.between}><View><Text style={[styles.brand, { color: primary }]}>{report.brand.displayName}</Text><Text style={[styles.overline, { color: accent, marginTop: 4 }]}>Local market read</Text></View><View><Text style={styles.date}>{report.scope.periodStart} to {report.scope.periodEnd}</Text><Text style={[styles.date, { marginTop: 3 }]}>Prepared {reportDate(report.generatedAt)}</Text></View></View><View style={styles.rule} /><View style={styles.hero}><Text style={[styles.overline, { color: accent }]}>{report.scope.marketName}</Text><Text style={[styles.title, { color: primary }]}>Your local asking market, observed clearly</Text><Text style={styles.narrative}>{report.marketRead.narrative}</Text></View><View style={[styles.scope, { backgroundColor: primary }]} wrap={false}><Text style={[styles.overline, { color: "#C7D6DD" }]}>Observed market scope</Text><Text style={styles.scopeValue}>{report.scope.totalObservedListings.toLocaleString("en-US")} listing observations</Text><Text style={styles.scopeText}>{report.scope.submarkets.join(" | ")} | houses and apartments by bedroom</Text></View><View style={styles.section}><Text style={[styles.overline, { color: accent }]}>Market read</Text><Text style={[styles.sectionTitle, { color: primary }]}>Rent level and direction by local segment</Text><Text style={styles.sectionIntro}>Level comes from Total IQ observed listings. Direction comes separately from validated Trends. Each number carries its sample and date.</Text><View style={styles.cards}>{cells.slice(0, 6).map((cell) => <Card key={cell.key} cell={cell} primary={primary} accent={accent} />)}</View></View><Footer brand={report.brand.displayName} pageNumber={1} /></Page>
    <Page size="LETTER" style={styles.page}><Text style={[styles.overline, { color: accent }]}>{report.scope.marketName}</Text><Text style={[styles.title, { color: primary, fontSize: 24 }]}>The local evidence behind the read</Text><Text style={styles.narrative}>Only statistically supported rent-level cells are published. A missing trajectory means the level is defensible but the latest local Trends sample is not.</Text><View style={styles.section}><View style={styles.table}><View style={styles.tableHeader}><Text style={[styles.c1, styles.tableLabel]}>Submarket</Text><Text style={[styles.c2, styles.tableLabel]}>Segment</Text><Text style={[styles.c3, styles.tableLabel]}>Median</Text><Text style={[styles.c4, styles.tableLabel]}>Per sf</Text><Text style={[styles.c5, styles.tableLabel]}>Trajectory</Text><Text style={[styles.c6, styles.tableLabel]}>N</Text></View>{cells.map((cell) => <View key={cell.key} style={styles.tableRow} wrap={false}><Text style={[styles.c1, { color: primary, fontWeight: 700 }]}>{cell.geographyLabel}</Text><Text style={styles.c2}>{cell.label}</Text><Text style={[styles.c3, { fontWeight: 700 }]}>{money(cell.rentLevel.medianAskingRent)}</Text><Text style={styles.c4}>{cell.rentLevel.medianRentPerSqFt === null ? "N/A" : `$${cell.rentLevel.medianRentPerSqFt.toFixed(2)}`}</Text><Text style={[styles.c5, { color: cell.trajectory ? accent : colors.muted }]}>{trend(cell)}</Text><Text style={styles.c6}>{cell.rentLevel.observations.toLocaleString("en-US")}</Text></View>)}</View></View><View style={styles.disclosure}><Text style={{ color: primary, fontWeight: 700 }}>Unavailable cut</Text><Text style={{ marginTop: 5 }}>{report.marketRead.unavailableCuts[0]?.reason ?? "No additional segment restrictions."}</Text></View><Footer brand={report.brand.displayName} pageNumber={2} /></Page>
    <Page size="LETTER" style={styles.page}><Text style={[styles.overline, { color: accent }]}>{report.scope.marketName}</Text><Text style={[styles.title, { color: primary, fontSize: 24 }]}>Conditions and the so-what</Text><View style={[styles.context, { backgroundColor: primary }]}><Text style={[styles.overline, { color: "#C7D6DD" }]}>Market conditions</Text><Text style={styles.contextTitle}>{report.marketConditions.heading}</Text><Text style={styles.contextText}>{report.marketConditions.narrative}</Text></View>{historical && <View style={styles.section}><Text style={[styles.overline, { color: accent }]}>At the Total IQ cutoff</Text><View style={styles.metricRow}><View style={styles.metric}><Text style={styles.tableLabel}>Active listings</Text><Text style={[styles.metricValue, { color: primary }]}>{historical.activeAtCutoff.toLocaleString("en-US")}</Text></View><View style={styles.metric}><Text style={styles.tableLabel}>New, 30 days</Text><Text style={[styles.metricValue, { color: primary }]}>{historical.newListings30d.toLocaleString("en-US")}</Text></View><View style={styles.metric}><Text style={styles.tableLabel}>Median DOM</Text><Text style={[styles.metricValue, { color: primary }]}>{Math.round(historical.medianDom)} days</Text></View><View style={styles.metric}><Text style={styles.tableLabel}>Median rent / sf</Text><Text style={[styles.metricValue, { color: primary }]}>${historical.medianRentPerSqFt.toFixed(2)}</Text></View></View></View>}<View style={styles.section}><Text style={[styles.overline, { color: accent }]}>Observed, not modeled</Text><Text style={[styles.sectionTitle, { color: primary }]}>Why these numbers are defensible</Text><Text style={styles.sectionIntro}>Every published figure carries a sample and date. Thin or conflicted cuts are withheld instead of estimated.</Text>{report.sources.map((source) => <View key={`${source.name}:${source.availableThrough}`} style={styles.source} wrap={false}><Text style={styles.sourceName}>{source.name}</Text><Text style={styles.sourceText}>Available through {source.availableThrough}{source.observationCount ? ` | ${source.observationCount.toLocaleString("en-US")} observations` : ""}</Text><Text style={styles.sourceText}>{source.note}</Text></View>)}<Text style={[styles.sourceText, { marginTop: 14 }]}>{report.methodNote}</Text><Text style={styles.disclosure}>{report.disclosure}</Text><Text style={[styles.sourceName, { color: primary, marginTop: 18 }]}>Prepared by {report.brand.displayName}</Text></View><Footer brand={report.brand.displayName} pageNumber={3} /></Page>
  </Document>;
}
