import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { DwellsyIqWorkspaceNav } from "@/components/dwellsy-iq/DwellsyIqWorkspaceNav";
import { getActiveOrgContext } from "@/lib/auth/active-org";
import { isMarketEntitled, resolveViewerEntitlement } from "@/lib/auth/market-entitlements.server";
import { viewerHasProductAccess } from "@/lib/auth/product-entitlements.server";
import { portfolioIqPreviewEnabled } from "@/lib/portfolio-iq/feature";
import { loadOwnerTeam } from "@/lib/portfolio-iq/team.server";
import type { OwnerTeamWorkItem } from "@/lib/portfolio-iq/team";
import { updatePortfolioDigestPreference } from "@/app/portfolio-iq/actions";
import { assignPortfolioDecisionMember } from "./actions";

export const dynamic = "force-dynamic";

function dateLabel(value: Date | null): string {
  return value ? value.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }) : "No due date";
}

function WorkCard({ item, members, currentUserId }: { item: OwnerTeamWorkItem; members: NonNullable<Awaited<ReturnType<typeof loadOwnerTeam>>>["members"]; currentUserId: string }) {
  return <article className="rounded-xl border border-grid bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center gap-2 text-[10px] font-bold uppercase tracking-wider"><span className={item.severity === "high" ? "text-rose-800" : "text-teal-700"}>{item.severity} priority</span><span className="text-muted-foreground">{item.state}</span></div><h3 className="mt-2 text-lg font-semibold leading-6 text-navy">{item.headline}</h3><p className="mt-2 text-xs text-muted-foreground">{item.assetNames.join(", ") || "Portfolio-level"} · {dateLabel(item.dueAt)}</p><div className="mt-4 flex flex-wrap gap-2 border-t border-grid pt-4"><Link href={`/today/cases/${item.signalId}`} className="rounded-md border border-grid px-3 py-2 text-xs font-semibold text-navy">Open decision</Link><form action={assignPortfolioDecisionMember} className="flex flex-1 gap-2"><input type="hidden" name="signalId" value={item.signalId} /><select name="assignedUserId" aria-label={`Assign ${item.headline}`} defaultValue={item.assignedUserId ?? currentUserId} className="min-w-0 flex-1 rounded-md border border-grid bg-white px-3 py-2 text-xs text-navy">{members.map((member) => <option key={member.userId} value={member.userId}>{member.isCurrentUser ? "Me" : member.name}</option>)}</select><button className="rounded-md bg-navy px-3 py-2 text-xs font-semibold text-white">Assign</button></form></div></article>;
}

export default async function OwnerTeamPage() {
  if (!portfolioIqPreviewEnabled() || !(await viewerHasProductAccess("portfolio_iq"))) notFound();
  const { userId, organizationId } = await getActiveOrgContext();
  if (!userId) notFound();
  if (!organizationId) redirect("/setup-workspace");
  const [data, entitlement] = await Promise.all([loadOwnerTeam({ userId, organizationId }), resolveViewerEntitlement()]);
  if (!data || !isMarketEntitled(entitlement, data.portfolio.marketId)) notFound();
  const { queue, members } = data;
  return <main className="mx-auto w-full max-w-7xl px-5 py-8 sm:px-6 lg:px-10 lg:py-10"><DwellsyIqWorkspaceNav />
    <header className="grid gap-6 border-b border-grid pb-8 lg:grid-cols-[1fr_360px] lg:items-end"><div><p className="dq-eyebrow">Owner team workspace</p><h1 className="dq-h1">My Work</h1><p className="mt-3 max-w-3xl text-[15px] leading-6 text-muted-foreground">Give every portfolio decision a real owner, see what is due, and keep briefing enrollment under each team member&apos;s control.</p></div><aside className="rounded-xl border border-teal/25 bg-teal-soft p-5"><p className="text-[10px] font-bold uppercase tracking-wider text-teal-700">Your queue</p><p className="mt-2 text-3xl font-semibold text-navy">{queue.mine.length}</p><p className="mt-1 text-sm text-foreground/75">active assignments · {queue.dueMine} due now</p></aside></header>
    <section className="mt-9"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="dq-eyebrow">Personal responsibility</p><h2 className="dq-h2">Assigned to me</h2></div><span className="rounded-full bg-navy px-3 py-1 text-xs font-semibold text-white">{queue.mine.length}</span></div>{queue.mine.length ? <div className="mt-5 grid gap-4 lg:grid-cols-2">{queue.mine.map((item) => <WorkCard key={item.signalId} item={item} members={members} currentUserId={userId} />)}</div> : <div className="mt-5 rounded-xl border border-dashed border-grid bg-white p-7 text-sm text-muted-foreground">No active decision is assigned to you. Claim an unassigned issue below when you are responsible for the next step.</div>}</section>
    <section className="mt-10 grid gap-6 lg:grid-cols-[1fr_0.72fr]"><div><p className="dq-eyebrow">Coverage gaps</p><h2 className="dq-h2">Unassigned owner decisions</h2>{queue.unassigned.length ? <div className="mt-5 space-y-4">{queue.unassigned.map((item) => <WorkCard key={item.signalId} item={item} members={members} currentUserId={userId} />)}</div> : <p className="mt-5 rounded-xl border border-dashed border-grid bg-white p-6 text-sm text-muted-foreground">Every active owner decision has an accountable person or operating role.</p>}</div><aside className="rounded-xl border border-grid bg-surface-soft p-5 sm:p-6"><p className="dq-eyebrow">Your briefing</p><h2 className="dq-h2">Personal delivery</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Each team member controls their own weekly briefing. Enrollment never sends mail to another person without that person signing in and opting in.</p><form action={updatePortfolioDigestPreference} className="mt-5 rounded-lg border border-grid bg-white p-4"><input type="hidden" name="portfolioId" value={data.portfolio.id} /><label className="flex items-start gap-3 text-sm font-semibold text-navy"><input type="checkbox" name="enabled" defaultChecked={data.currentPreference?.enabled ?? false} className="mt-1" /><span>Email my weekly owner briefing<span className="mt-1 block text-xs font-normal text-muted-foreground">Only after material evidence or decision changes.</span></span></label><button className="mt-4 rounded-md bg-navy px-3 py-2 text-xs font-semibold text-white">Save my preference</button></form></aside></section>
    <section className="mt-10 border-t border-grid pt-8"><div><p className="dq-eyebrow">Team coverage</p><h2 className="dq-h2">Who owns the response</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{members.map((member) => <article key={member.userId} className="rounded-xl border border-grid bg-white p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-navy">{member.name}{member.isCurrentUser ? " (you)" : ""}</h3><p className="mt-1 text-xs text-muted-foreground">{member.email || "Identity available after Clerk sync"}</p></div><span className="rounded-full bg-surface-soft px-2 py-1 text-[10px] font-bold uppercase text-muted-foreground">{member.role.replace("org:", "")}</span></div><div className="mt-4 grid grid-cols-2 gap-2 border-t border-grid pt-4 text-sm"><div><p className="text-2xl font-semibold text-navy">{member.activeAssignments}</p><p className="text-xs text-muted-foreground">active decisions</p></div><div><p className="text-sm font-semibold text-navy">{member.briefingEnabled ? "Enabled" : "Off"}</p><p className="text-xs text-muted-foreground">weekly briefing</p></div></div></article>)}</div></section>
    {queue.delegated.length > 0 && <section className="mt-10"><p className="dq-eyebrow">Delegated work</p><h2 className="dq-h2">Assigned to another team member</h2><div className="mt-5 grid gap-4 lg:grid-cols-2">{queue.delegated.map((item) => <WorkCard key={item.signalId} item={item} members={members} currentUserId={userId} />)}</div></section>}
    {queue.roleOrExternal.length > 0 && <section className="mt-10 rounded-xl border border-grid bg-surface-soft p-5 sm:p-6"><p className="dq-eyebrow">Operating responsibility</p><h2 className="dq-h2">Assigned to a role or external partner</h2><div className="mt-4 divide-y divide-grid">{queue.roleOrExternal.map((item) => <div key={item.signalId} className="flex flex-wrap items-center gap-3 py-3 text-sm"><Link href={`/today/cases/${item.signalId}`} className="font-semibold text-navy hover:text-teal-700">{item.headline}</Link><span className="rounded-full bg-white px-2 py-1 text-xs text-muted-foreground">{item.assignedTo}</span><span className="ml-auto text-xs text-muted-foreground">{dateLabel(item.dueAt)}</span></div>)}</div></section>}
  </main>;
}
