import { notFound } from "next/navigation";
import { loadPublicPortfolioIqPmBrief } from "@/lib/portfolio-iq/pm-brief.server";
import { submitPortfolioIqPmBriefResponse } from "../actions";

export const dynamic = "force-dynamic";

function money(value: number | null): string { return value === null ? "Not enough evidence" : `$${Math.round(value).toLocaleString("en-US")}`; }
function percent(value: number | null): string { return value === null ? "Not enough evidence" : `${value >= 0 ? "+" : ""}${value.toFixed(1)}%`; }
function dateLabel(value: string | Date | null): string { return value ? new Date(value).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric", timeZone: "UTC" }) : "Not specified"; }

export default async function PublicPmBriefPage({ params, searchParams }: { params: Promise<{ publicToken: string }>; searchParams: Promise<{ submitted?: string }> }) {
  const { publicToken } = await params;
  const query = await searchParams;
  const loaded = await loadPublicPortfolioIqPmBrief(publicToken);
  if (!loaded) notFound();
  const { brief, snapshot } = loaded;
  const responded = Boolean(brief.response) || brief.status === "responded" || query.submitted === "1";
  return <main className="mx-auto w-full max-w-5xl px-5 py-10 sm:px-6 lg:py-14"><header className="border-b border-grid pb-8"><p className="text-[11px] font-bold uppercase tracking-[0.15em] text-teal-700">Dwellsy IQ · Property discussion</p><h1 className="mt-3 max-w-4xl text-3xl font-semibold leading-tight tracking-tight text-navy sm:text-5xl">{snapshot.property.name}</h1><p className="mt-3 text-sm text-muted-foreground">{snapshot.property.address}, {snapshot.property.city}, {snapshot.property.state} {snapshot.property.postalCode}</p><div className="mt-5 flex flex-wrap gap-2 text-xs"><span className="rounded-full border border-grid bg-white px-3 py-1.5 text-navy">{snapshot.property.product}</span><span className="rounded-full border border-grid bg-white px-3 py-1.5 text-navy">Evidence through {dateLabel(snapshot.evidence.availableThrough)}</span>{snapshot.request.responseDueAt && <span className="rounded-full border border-amber-200 bg-amber-50 px-3 py-1.5 text-amber-900">Response requested by {dateLabel(snapshot.request.responseDueAt)}</span>}</div></header>
    <section className="mt-8 rounded-xl border border-teal/25 bg-teal-soft p-5 sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-teal-700">Question for the property manager</p><h2 className="mt-2 text-2xl font-semibold leading-8 text-navy">{snapshot.issue.headline}</h2><p className="mt-3 text-sm leading-6 text-foreground/75">{snapshot.issue.narrative}</p>{snapshot.request.ownerNote && <div className="mt-5 rounded-lg border border-white bg-white/80 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Owner context</p><p className="mt-2 text-sm leading-6 text-navy">{snapshot.request.ownerNote}</p></div>}</section>
    <section className="mt-7 overflow-hidden rounded-xl border border-grid bg-white shadow-sm"><div className="border-b border-grid p-5"><p className="text-[10px] font-bold uppercase tracking-wider text-teal-700">Evidence being discussed</p><p className="mt-2 text-sm leading-6 text-muted-foreground">These are advertised asking-market observations, not an assessment of the manager.</p></div><div className="grid gap-px bg-grid sm:grid-cols-2 lg:grid-cols-4">{[["Observed asking rent", money(snapshot.evidence.askingRent), `${snapshot.evidence.observationCount} observations`], ["90-day movement", percent(snapshot.evidence.askingRentChange90d), "Advertised asking rent"], ["Listing velocity", snapshot.evidence.medianDom === null ? "Not enough evidence" : `${Math.round(snapshot.evidence.medianDom)} days`, "Advertised duration"], ["Position vs comps", percent(snapshot.evidence.askingRentVsComps), snapshot.evidence.compStatus === "locked" ? `${snapshot.evidence.compCount} approved comps` : "Not shown until reviewed"]].map(([label, value, detail]) => <article key={label} className="bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 text-xl font-semibold text-navy">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></article>)}</div>{snapshot.marketContext && <div className="border-t border-grid bg-surface-soft p-5"><p className="text-[10px] font-bold uppercase tracking-wider text-teal-700">Local asking-market context</p><h3 className="mt-2 font-semibold text-navy">{snapshot.marketContext.headline}</h3><p className="mt-1 text-sm leading-6 text-foreground/75">{snapshot.marketContext.narrative}</p></div>}</section>
    <section className="mt-7 grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><article className="rounded-xl border border-grid bg-white p-5 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-wider text-teal-700">Requested response</p><ol className="mt-4 space-y-3">{snapshot.request.questions.map((question, index) => <li key={question} className="flex gap-3 text-sm leading-6 text-navy"><span className="font-bold text-teal-700">{index + 1}.</span><span>{question}</span></li>)}</ol><p className="mt-5 border-t border-grid pt-4 text-xs leading-5 text-muted-foreground">{snapshot.disclosure}</p></article>
    {responded ? <article className="rounded-xl border border-emerald-200 bg-emerald-50 p-6"><p className="text-[10px] font-bold uppercase tracking-wider text-emerald-800">Response received</p><h2 className="mt-2 text-2xl font-semibold text-navy">Thank you</h2><p className="mt-2 text-sm leading-6 text-emerald-900/80">Your response has been added to the owner&apos;s property decision record. No other portfolio information is available through this link.</p></article> : brief.status === "published" ? <article className="rounded-xl border border-navy bg-navy p-5 text-white sm:p-6"><p className="text-[10px] font-bold uppercase tracking-wider text-teal-200">Respond to the owner</p><form action={submitPortfolioIqPmBriefResponse} className="mt-4 grid gap-4 sm:grid-cols-2"><input type="hidden" name="publicToken" value={publicToken} /><label className="text-sm font-semibold">Your name<input name="responderName" required minLength={2} maxLength={120} className="mt-2 w-full rounded-md border border-white/20 bg-white px-3 py-2.5 text-sm font-normal text-navy" /></label><label className="text-sm font-semibold">Email, optional<input type="email" name="responderEmail" maxLength={254} className="mt-2 w-full rounded-md border border-white/20 bg-white px-3 py-2.5 text-sm font-normal text-navy" /></label><label className="sm:col-span-2 text-sm font-semibold">What should the owner know?<textarea name="responseSummary" required minLength={20} maxLength={2500} rows={5} className="mt-2 w-full rounded-md border border-white/20 bg-white px-3 py-2.5 text-sm font-normal leading-6 text-navy" /></label><label className="sm:col-span-2 text-sm font-semibold">Recommended action, optional<textarea name="actionPlan" maxLength={1500} rows={3} className="mt-2 w-full rounded-md border border-white/20 bg-white px-3 py-2.5 text-sm font-normal leading-6 text-navy" /></label><label className="text-sm font-semibold">Follow-up date, optional<input type="date" name="followUpDate" className="mt-2 w-full rounded-md border border-white/20 bg-white px-3 py-2.5 text-sm font-normal text-navy" /></label><label className="hidden" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off" /></label><div className="flex items-end"><button className="w-full rounded-md bg-white px-4 py-2.5 text-sm font-semibold text-navy">Submit response</button></div></form></article> : <article className="rounded-xl border border-grid bg-surface-soft p-6"><h2 className="text-xl font-semibold text-navy">This discussion is closed</h2><p className="mt-2 text-sm text-muted-foreground">Contact the owner directly if additional context is needed.</p></article>}</section>
  </main>;
}
